site_name: QML Core UI
site_description: guide to the core ui architecture for QML driven projects
site_author: Juergen Ryannel
copyright: 2019 Luxoft GmbH
repo_url: https://github.com/Luxoft/qml-coreui-guide
google_analytics:

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "teal"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  logo:
    icon: "bookmark"
  language: "en"
  extra:
    search:
      language: "en"
  feature:
    tabs: true

nav:
  - "Home": index.md
  - "Tutorial":
      - "Overview": "guide/overview.md"
      - "Install": "guide/install.md"
      - "Getting Started": "guide/start.md"
      - "CookBook": "guide/cookbook.md"
      - "Examples": "guide/examples.md"
  - Topics:
      - "Foundations": "topics/foundations.md"
      - "Building Blocks": "topics/blocks.md"
      - "UI Layer": "topics/uilayer.md"
      - "Filesystem layout": "topics/fslayout.md"
      - "Runtime & Modules": "topics/runtime.md"
      - "Kind of Components": "topics/kind.md"
      - "Controls": "topics/controls.md"
      - "Services": "topics/services.md"
      - "Testing": "topics/testing.md"
      - "Styles": "topics/styles.md"
      - "Layouts": "topics/layouts.md"
      - "Protoyping": "topics/prototyping.md"
      - "Exposing Data to QML": "topics/data.md"
      - "Design Work Flow": "topics/workflow.md"
      - "(Live) Reloading": "topics/reload.md"
      - "Refactoring": "topics/refactor.md"
      - "Design Principles": "topics/principles.md"
      - "UI Process Modes": "topics/process.md"
  - Admin CLI:
      - "Introduction": "admin/intro.md"
      - "Quick Start": "admin/start.md"
      - "Concepts": "admin/concepts.md"
      - "Building": "admin/build.md"
      - "Developing": "admin/dev.md"
      - "Project Creation": "admin/projects.md"
      - "Reference": "admin/reference.md"

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.magiclink
